name: UltimateServerPlugin2
main: com.minkang.ultimate.Main
version: 1.4.50
api-version: 1.16
author: MinGang
softdepend: [Vault, Essentials, Citizens]

commands:
  개체값:
    description: Pixelmon IVs (한글)

  노력치:
    description: Pixelmon EVs (한글)

  알걸음:
    description: Pixelmon eggsteps (한글)

  배틀종료:
    description: Pixelmon endbattle
    permission: usp.battle

  돈:
    description: 잔액/송금/순위
    aliases: [balance, bal]

  수표:
    description: 수표 발급(소지금 차감, 무권한)

  수리권:
    description: 수리권
    permission: usp.fix.admin

  수리권 발급:
    description: 수리권 발급
    permission: usp.fix.admin

  상점:
    description: 상점 열기/관리
    permission: usp.shop.admin

  상점리로드:
    description: 상점 리로드
    permission: usp.shop.admin

  야투:
    description: 야간투시
# TRADE_DISABLED
# 
