name: UltimateServerPlugin2
main: com.minkang.ultimate.Main
version: 1.4.25
api-version: 1.16
author: MinGang
softdepend: [Vault, Essentials, Citizens]
commands:
  개체값:
    description: Pixelmon IVs (한글)
    
  노력치:
    description: Pixelmon EVs (한글)
    
  알걸음:
    description: Pixelmon eggsteps (한글)
    
  배틀종료:
    description: Pixelmon endbattle
    permission: usp.battle

  돈:
    description: 잔액/송금/순위
    aliases: [balance, bal]

  수표:
    description: 수표 발급(소지금 차감, 무권한)

  수리권:
    description: 수리권 발급
    default: op
    
  상점:
    description: 상점 열기/관리
    permission: usp.shop.admin
    default: op
    
  야투:
    description: 야간투시

  거래:
    description: 거래/신청
    
  잠금:
    description: 잠금실행
    
  잠금권:
    description: 상점 열기/관리
    permission: usp.locks.admin
    default: op
    
  전체지급:
    description: 손에 든 아이템을 전체에게 지급
    permission: usp.globalgive
    default: op
    
  추첨:
    description: 3 2 1 카운트다운 후 랜덤 당첨자 발표
    permission: usp.raffle
    default: op
    
  기본템:
    description: 기본템 수령/설정/초기화

permissions:
  usp.shop.admin:
    default: op
  usp.globalgive:
    default: op
  usp.raffle:
    default: op
  usp.kit.setup:
    default: op
  usp.kit.reset:
    default: op
  usp.locks.admin:
    default: op
